# Generated by Django 5.1.3 on 2025-03-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True, verbose_name='Kitob nomi')),
                ('description', models.TextField(verbose_name='Kitob tavsifi')),
                ('price', models.FloatField(verbose_name='Kitob narxi')),
                ('quantity', models.IntegerField(verbose_name='Kitob soni')),
                ('image', models.ImageField(upload_to='media', verbose_name='Mahsulot rasmi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
            ],
        ),
        migrations.CreateModel(
            name='refrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='refrences nomi')),
                ('value', models.CharField(max_length=255, verbose_name='refrences qiymati')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Xarajat narxi')),
                ('description', models.TextField(verbose_name='Xarajat malumoti')),
                ('quantity', models.IntegerField(verbose_name='Xarajat miqdori')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Xarajat sanasi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs_as_name', to='home.book_model', verbose_name='Xarajat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Sotilgan kitob soni')),
                ('price', models.FloatField(verbose_name='Sotilgan kitob narxi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Sotilgan kitob sanasi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('sold_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book_model', verbose_name='Sotilgan kitob nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Chiqim narxi')),
                ('description', models.TextField(verbose_name='Chiqim malumoti')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Chiqim sanasi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.refrences', verbose_name='Chiqim nomi')),
            ],
        ),
        migrations.AddField(
            model_name='book_model',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='home.refrences', verbose_name='Kitob turi'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="Xodimning to'liq ismi")),
                ('phone_number', models.TextField(verbose_name='Xodimning telefon raqami')),
                ('birthday', models.DateField(verbose_name='Xodimning tug‘ilgan sanasi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='O‘chirilganmi?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Qo‘shilgan sana')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.refrences', verbose_name='Xodimning jinsi')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='tolangan summa')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='tolov sanasi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff', verbose_name='xodim')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Ishlagan xodimning maoshi')),
                ('time_work', models.FloatField(verbose_name='Ishlagan xodimning ish vaqti')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='tolov sanasi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff', verbose_name='Ishlagan xodim')),
            ],
        ),
    ]
