# Generated by Django 5.1.3 on 2024-12-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_as_category', to='home.refrences', verbose_name='Kitob turi'),
        ),
        migrations.AlterField(
            model_name='book_model',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_as_name', to='home.refrences', verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs_as_category', to='home.refrences', verbose_name='Xarajat turi'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs_as_name', to='home.refrences', verbose_name='Xarajat nomi'),
        ),
        migrations.AlterField(
            model_name='income',
            name='sold_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.refrences', verbose_name='Sotilgan kitob nomi'),
        ),
        migrations.AlterField(
            model_name='output',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.refrences', verbose_name='Chiqim nomi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.refrences', verbose_name='Xodimning jinsi'),
        ),
        migrations.AlterField(
            model_name='staff_work',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff', verbose_name='Ishlagan xodim'),
        ),
    ]
