# Generated by Django 5.1.3 on 2025-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_staff_payment_is_deleted_staff_work_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
