# Generated by Django 5.1.3 on 2025-01-27 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_output_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_work',
            name='paid_price',
        ),
        migrations.AddField(
            model_name='staff_work',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='tolov sanasi'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Staff_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='tolangan summa')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='tolov sanasi')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff', verbose_name='xodim')),
            ],
        ),
    ]
